# NumPy Installing and importing the library

In [1]:
import numpy as np

# Creating NumPy Array

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
arr[0]=9
print(arr) # Mutable 

arr_2D=np.array([[1,2],[3,4]])
print(arr_2D)

[1 2 3 4 5]
[9 2 3 4 5]
[[1 2]
 [3 4]]


# List v/s Array

In [ ]:
list=[1,2,3,4,5]
print(list*2)

arr=np.array([1,2,3,4,5]) # 1D vector ki tarah hai yeh
print(arr*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


# Comparing List v/s Array

In [ ]:
import time

start=time.time()
list=[i*2 for i in range(1000000)]
print("Time taken by list comprehension:",time.time()-start)

start=time.time()
arr=np.arange(1000000)*2 #np.arrange([i*2 for i in range(1000000)]) yeh nhi likhna hai
print("Time taken by numpy array:",time.time()-start)



Time taken by list comprehension: 0.19635486602783203
Time taken by numpy array: 0.029928207397460938


# Types of array we can make simply
# zeros
# ones
# scalar using full
# identity using eye
# random using random.random
# sequence using (start,stop,step)

In [ ]:
zeros=np.zeros((2,2))
print(zeros)

ones=np.ones((2,2))
print(ones)

full=np.full((2,2),9)
print(full)

# Identity Matrix of order n
eye=np.eye(3)
print(eye)

random=np.random.random((2,2))
print(random)

seq=np.arange(0,10,3)
print(seq)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.3173876  0.16726247]
 [0.7475003  0.39106684]]
[0 3 6 9]


# Tensor kya hota hai 3D array

In [10]:
Tensor=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(Tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


# Properties of an Array

In [ ]:
arr=np.array([[1,8,4],[2,7,0],[3,6,4]])

print("Size:",arr.size) # row * column
print("Shape:",arr.shape)
print("Dimension:",arr.ndim) # 2-D array hi toh hai
print("Dtype:",arr.dtype)

Size: 9
Shape: (3, 3)
Dimension: 2
Dtype: int64


# How to reshape an array 
# flatten() v/s ravel()

In [19]:
arr1=np.arange(12)
print(arr1)

arr2=arr1.reshape((3,4))
print(arr2)

arr3=arr2.flatten()
print(arr3)

arr4=arr2.ravel()
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Transpose of an Array

In [21]:
arr=arr2.T
print(arr)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
