# Revision and Practice


In [2]:
import numpy as np

In [ ]:
arr=np.array([6,4,2,5,1,3,7])

## Statistics

In [ ]:
print("Sum ", np.sum(arr))

print("Mean",np.mean(arr))

print("Median", np.median(arr))

print("Standard Variance", np.std(arr))

print("Variance",np.var(arr))

print("Min",np.min(arr))

print("Argmin ",np.argmin(arr))

print("Max",np.max(arr))

print("argmax",np.argmax(arr))

Sum  28
Mean 4.0
Median 4.0
Standard Variance 2.0
Variance 4.0
Min 1
Argmin  4
Max 7
argmax 6


## Create


In [10]:
zero=np.zeros((3,3))
ones=np.ones((3,3))
scalar=np.full((3,3),4)
identity=np.eye(3,3)
empty=np.empty((3,3))
random=np.random.random((3,3))
range=np.arange(2,12,3)
linspace=np.linspace(2,12,3)

In [11]:
print(zero)
print(ones)
print(scalar)
print(identity)
print(random)
print(range)
print(linspace)
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.06485791 0.00668912 0.69332748]
 [0.7392194  0.05140311 0.81413693]
 [0.20768503 0.51145109 0.2373409 ]]
[ 2  5  8 11]
[ 2.  7. 12.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
print(np.sqrt(arr))

print(np.exp(arr))

print(np.log(arr))

print(np.sin(arr))

print(np.cos(arr))

print(np.round(arr))

print(np.abs(arr))

print(np.sort(arr))


[2.44948974 2.         1.41421356 2.23606798 1.         1.73205081
 2.64575131]
[ 403.42879349   54.59815003    7.3890561   148.4131591     2.71828183
   20.08553692 1096.63315843]
[1.79175947 1.38629436 0.69314718 1.60943791 0.         1.09861229
 1.94591015]
[-0.2794155  -0.7568025   0.90929743 -0.95892427  0.84147098  0.14112001
  0.6569866 ]
[ 0.96017029 -0.65364362 -0.41614684  0.28366219  0.54030231 -0.9899925
  0.75390225]
[6 4 2 5 1 3 7]
[6 4 2 5 1 3 7]
[1 2 3 4 5 6 7]


In [19]:
np.round(random)

array([[0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 0.]])

In [21]:
np.abs(np.array([-2,2.3,-5]))

array([2. , 2.3, 5. ])

In [56]:
mat1=np.array([[2,3],[4,5]])
mat2=np.array([[6,7],[2,3]])

In [27]:
np.matmul(mat1,mat2)

array([[18, 23],
       [34, 43]])

In [28]:
arr1=np.array([3,5,2])
arr2=np.array([1,4,6])

In [40]:
print("Dot Product",np.dot(arr1,arr2))
print("Inverse of a matrix ",np.linalg.inv(mat1))
print("Determinant of matrix ",np.linalg.det(mat1))
print("eigen value of a matrix ",np.linalg.eig(mat1))
print("Magnitude of a vector",np.linalg.norm(arr1))

Dot Product 35
Inverse of a matrix  [[-2.5  1.5]
 [ 2.  -1. ]]
Determinant of matrix  -2.0
eigen value of a matrix  EigResult(eigenvalues=array([-0.27491722,  7.27491722]), eigenvectors=array([[-0.79681209, -0.49436913],
       [ 0.60422718, -0.86925207]]))
Magnitude of a vector 6.164414002968976


In [ ]:
angle=np.arccos((np.dot(arr1,arr2))/((np.linalg.norm(arr1))*(np.linalg.norm(arr2))))

In [48]:
print("shape ",mat1.shape)
print("size",mat1.size)
print("dimension",mat1.ndim)
print("bytes",mat1.nbytes)
print("datatype",mat1.dtype)
print("each element byte",mat1.itemsize)

shape  (2, 2)
size 4
dimension 2
bytes 32
datatype int64
each element byte 8


In [51]:
mat1

array([[2, 3],
       [4, 5]])

In [49]:
mat1.T

array([[2, 4],
       [3, 5]])

In [50]:
mat1.transpose()

array([[2, 4],
       [3, 5]])

In [52]:
mat1.reshape(1,4)

array([[2, 3, 4, 5]])

In [57]:
mat1

array([[2, 3],
       [4, 5]])

In [58]:
mat1.resize(1,4)

In [59]:
mat1

array([[2, 3, 4, 5]])

In [68]:
np.any(identity)

np.True_

In [70]:
np.all(identity)

np.False_

In [72]:
np.isnan(identity)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [74]:
np.isinf(identity)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [76]:
np.unique(identity)

array([0., 1.])

In [ ]:
original=np.array([[2,5],[3,4]])
row=np.array([[6,7]]) #new row which we want to add in matrix
column=np.array([[6],[7]]) # column which we want to add in matrix

row_add=np.vstack([original,row]) # row added
col_add=np.hstack([original,column]) # column added

In [80]:
row_add

array([[2, 5],
       [3, 4],
       [6, 7]])

In [ ]:
col_add 

array([[2, 5, 6],
       [3, 4, 7]])

In [ ]:
new=np.dstack([original,mat2]) #tensor creation using two same dimension matrices or tensor

In [ ]:
new #tensor

array([[[2, 6],
        [5, 7]],

       [[3, 2],
        [4, 3]]])

In [94]:
col_add[:,0]

array([2, 3])

In [95]:
row_add[:2]

array([[2, 5],
       [3, 4]])

In [98]:
row_add[0,1]

np.int64(5)

In [ ]:
indices=np.where(arr < 5)

In [107]:
indices

(array([1, 2, 4, 5]),)

In [108]:
arr

array([6, 4, 2, 5, 1, 3, 7])

In [109]:
arr[indices]

array([4, 2, 1, 3])