# Importing the library is the 1st step Mandatory 

In [2]:
import numpy as np

# Slicing operation just similar to list 

In [ ]:
arr=np.array([ [3,2,6], [4,1,5], [5,8,9] ])
print(arr[0,1]) # Specific Element
print(arr[0]) # Entire Row
print(arr[:,1]) # Entire Column


2
[3 2 6]
[2 1 8]


# Sorting array wrt row or column

In [8]:
arr1=np.array([3,6,5,1,4,7,9,8,2])
print("Sorted",np.sort(arr1)) # Sorting array

arr2=np.array([ [5,3,4], [2,8,1], [9,7,6] ])
print("Sorted by column", np.sort(arr2, axis = 0)) # Sorting by Column
print("Sorted by row", np.sort(arr2, axis = 1)) # Sorting by Row

Sorted [1 2 3 4 5 6 7 8 9]
Sorted by column [[2 3 1]
 [5 7 4]
 [9 8 6]]
Sorted by row [[3 4 5]
 [1 2 8]
 [6 7 9]]


# Mask/ Condition

In [ ]:
arr1=np.array([3,6,5,1,4,7,9,8,2])
even=arr1[ arr1 % 2 == 0 ] # (arr1 % 2 == 0) is mask
print(even)

[6 4 8 2]


# Similar to above operation

In [32]:
mask = arr1 > 5 
arr2=arr1[mask]
print(arr2)

[6 7 9 8]


# We are creating a variable which stores indices value as a list

In [ ]:
index=np.where( arr1 < 5 )
print(index)
print("array: ",arr1[index])

(array([0, 3, 4, 8]),)
array:  [3 1 4 2]


# Condition+Masking

In [18]:
arr=np.array([3,2,7,6,8,4,5,9,1])
condition= np.where(arr>5,"True","False")
print(condition)

['False' 'False' 'True' 'True' 'True' 'False' 'False' 'True' 'False']


# Adding v/s Concatenation

In [13]:
arr1=np.array([1,2,3,4])

arr2=np.array([5,6,7,8])
print(arr1+arr2)
arr3=np.concatenate((arr1,arr2))
print(arr3)

[ 6  8 10 12]
[1 2 3 4 5 6 7 8]


# Compatibility Test 

In [38]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
c=np.array([5,6,7,8,9])
print("Compatibility",a.shape==b.shape)
print("Compatibility",a.shape==c.shape)
print("Compatibility",c.shape==b.shape)

Compatibility True
Compatibility False
Compatibility False


# Adding row or column and deletion of data

In [10]:
a1=np.array([[1,2],[3,4]])

row=np.array([[5,6]]) #we are adding a row

new_a1=np.vstack((a1,row)) #vstack means vertical
print(new_a1)

column=np.array([[7],[8]])

new_a2=np.hstack((a1,column)) #hstack means horizontal
print(new_a2)

arr1=np.array([4,3,6,7,2,8])
delete=np.delete(arr1,2) # element delete karta hai
print(delete)



[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
[4 3 7 2 8]
